---
output: revealjs::revealjs_presentation
---

```{r setup, include = F}
library(knitr)
library(tidyverse)
library(yose)
yose::set_reveal_hooks()

p <-
 lapply(2:5, function(x){
   tibble(x = 1:5, y = x * 2)[1:x, ] %>%
     ggplot(aes(x, y)) +
     geom_point() +
     geom_line() +
     lims(x = c(0, 5), y = c(0, 10))
 })
```



# Demo

## default display

<div style="position:relative; top:0px; width:800px; height:600px; margin:0 auto;">
```{r demo_default, echo = F}
p[[2]]
```
</div>
<div class="fragment" data-fragment-index="1">- plot points</div>

## incremental display with chunk options

<div style="position:relative; top:0px; width:800px; height:600px; margin:0 auto;">
```{r demo_chunk1, fragment_index = 1, echo = F}
p[[2]]
```

```{r demo_chunk2, fragment_style = 'fragment fade-up', fragment_index = 3, echo = F}
p[[3]]
```
</div>
<div class="fragment" data-fragment-index="2">- plot points</div>
<div class="fragment" data-fragment-index="4">- add a comment</div>

## incremental display with `kamishibai`

`r yose::kamishibai(p)`



# Appendix

## `.Rmd` code 

Check [`r icon::fa("github")`](https://github.com/KeachMurakami/yose/blob/master/demo.Rmd).


## Session information

```{r}
devtools::session_info()
```
