---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# yose (寄席)

This package implements incremental figure display in {revealjs} slide.
`yose` is a Japanese word meaning storytelling [-> Google Images](https://www.google.co.jp/search?q=%E5%AF%84%E5%B8%AD&source=lnms&tbm=isch&sa=X&ved=0ahUKEwix35LSoYHaAhVJlJQKHQKKARYQ_AUICygC&biw=1280&bih=924).


## Usage

You can install the latest development version from github with

```{r, eval = F}
# install.packages("devtools") # if not installed
devtools::install_github("KeachMurakami/yose")
```

See [`.html`](https://github.com/KeachMurakami/yose/blob/master/demo.html) generated by [`.Rmd`](https://github.com/KeachMurakami/yose/blob/master/demo.Rmd) with this package.

## LICENCE

This package is free and open source software, licensed under GPL.

## Session information

```{r sessioninfo, echo = F}
library(knitr)
library(revealjs)
library(rmarkdown)
devtools::session_info()
```
